spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 20MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tms_postgresql?currentSchema=tms
    username: lena
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 5000 # in msecs
